[build]
  publish = "site/public"
  command = "yarn build --all && (cd site && yarn build)"

[build.environment]
  YARN_VERSION = "1.12.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
